### ISSUE TITLE
might want to check this out

### ISSUE THREAD

**Issue by monkpearman** [white-flame/clyc#1]
https://github.com/logicmoo/CYC_JRTL_with_CommonLisp

there are additional CYC related CL projects on their profile.

**Comment by white-flame** [comment]
Yeah, I've known Doug (of LogicMOO, not Lenat) for many years. I've looked through a lot of his stuff for reference. My specific goals were to learn some of the specific Cyc implementation strategies around its multiple inference layers, not necessarily how others implemented informed Cyc-alikes which unify things together. I am, however, working on different styles of neuro-symbolic inference that make some of my explorations here into Cyc somewhat redundant. But I'll make sure to look through the logicmoo repos again to see what's come up in the meantime.  Thanks for sharing, and it's a good link for others, too.
